apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: humhub-ingress
  namespace: humhub
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: web #traefik de serie, que vaya al puerto 80 (http)
spec:
  rules:
  - host: humhub.grupo7.com #dominio de la web
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: humhub-service 
            port:
              number: 80